tests for `7-base_geometry` module
=====================================================

importing module class BaseGeometry module:
	>>> BaseGeometry = __import__("7-base_geometry").BaseGeometry

creating an instance of the class `BaseGeometry`
>>> bg = BaseGeometry()

trying to print area
>>> bg.area()
Traceback (most recent call last):
  ...
Exception: area() is not implemented

passing 1 argument to area
>>> bg.area(3)
Traceback (most recent call last):
 ...
TypeError: area() takes 1 positional argument but 2 were given

passing 2 arguments to method
>>> bg.area(3, 5)
Traceback (most recent call last):
 ...
TypeError: area() takes 1 positional argument but 3 were given

passing a negative number
>>> bg.integer_validator("height", -175)
Traceback (most recent call last):
   ...
ValueError: height must be greater than 0

passing a non integer
>>> bg.integer_validator("speed", "45km/hr")
Traceback (most recent call last):
  ...
TypeError: speed must be an integer

passing zero
>>> bg.integer_validator("height", 0)
Traceback (most recent call last):
   ...
ValueError: height must be greater than 0

passing a positive integer greater than zero
>>> bg.integer_validator("mass", 71)

passing bool as argument
>>> bg.integer_validator("fast", True)
Traceback (most recent call last):
  ...
TypeError: fast must be an integer

passing None
>>> bg.integer_validator("paste", None)
Traceback (most recent call last):
  ...
TypeError: paste must be an integer

passing a list
>>> bg.integer_validator("pasta", [5, 76])
Traceback (most recent call last):
  ...
TypeError: pasta must be an integer

passing a tuple
>>> bg.integer_validator("score", (5, 76))
Traceback (most recent call last):
  ...
TypeError: score must be an integer

passing a non-string as the first function
>>> bg.integer_validator(56, 45)

if no argument is passed
>>> bg.integer_validator()
Traceback (most recent call last):
  ...
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

passing only one argument
>>> bg.integer_validator("s")
Traceback (most recent call last):
  ...
TypeError: integer_validator() missing 1 required positional argument: 'value'

passing dict
>>> bg.integer_validator("dictionary", {'age': 20, "favorite series": "one piece"})
Traceback (most recent call last):
  ...
TypeError: dictionary must be an integer

passing 3 arguments
>>> bg.integer_validator("name", 1, 2)
Traceback (most recent call last):
    	      ...
TypeError: integer_validator() takes 3 positional arguments but 4 were given
